name: Build

on:
  workflow_dispatch:
  release:
    types:
      - published


concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-13, macos-14 ]
        arch: [ auto64 ]
        build: [ "cp{38,39,310,311,312,313}-*"]      

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: "pypa/cibuildwheel@v3.0.1"
        env:
           CIBW_BUILD: ${{ matrix.build }}
           CIBW_ARCHS: ${{ matrix.arch }}
           CIBW_SKIP: "pp* *-win32 *-manylinux_i686 *-musllinux* cp313-*"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest    
    #if: github.event_name == 'release' && github.event.action == 'published'
    environment: 
      name: pypi
      url: https://pypi.org/p/pycatima
    permissions:
      id-token: write
    steps:      
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:          
          verify-metadata: false
